### PR TITLE
Switch to Go modules

### LINKED ISSUE #13: Is the project still maintained?
Hi - I wanted to check if the project is still maintained. If yes, would you be open to a PR with the following changes?
* switch from vendoring dependencies to using Go modules
* replace the current go-powershell dependency with https://github.com/antoninbas/go-powershell. This fork converts the project to Go modules and removes the dependency on juju packages (which are distributed under an LGPL v3 license, making usage in commercial products difficult)

Additionally, would you be willing to make a Github release/ create a tag after making the changes above?

Thanks

### PR DESCRIPTION
**Pull request by antoninbas**
* Switch to Go modules and remove vendoring
* Use different fork of go-powershell: replace the current go-powershell
  dependency with https://github.com/antoninbas/go-powershell. This fork
  converts the project to Go modules and removes the dependency on juju
  packages (which are distributed under an LGPL v3 license, making usage
  in commercial products difficult)
* Enable CI: run unit tests using Github workflows

Fixes #13

### CODE REVIEW

**Comment by antoninbas** [comment]
@rakelkar could you enable Github actions in this repo so the tests can run?

**Comment by rakelkar** [comment]
Hey Antonio - thanks for your PR - quick qn, did you try to get your changes in go-powershell updated to benmoss repo?

**Comment by antoninbas** [comment]
@rakelkar I wasn't planning on doing it, since `benmoss/go-powershell` is already a fork and the original project seems to be unmaintained. Is that an issue for you? If yes, I can try to reach out to benmoss.

**Comment by rakelkar** [comment]
Would be great if you can try to get an okay from benmoss him as a curtsy :)

**Comment by rakelkar** [comment]
have enabled actions btw!

**Comment by antoninbas** [comment]
I have opened the PR: https://github.com/benmoss/go-powershell/pull/1

If it's accepted, I'll update this PR. Looks like there are some unit tests failures, so I'll address them as well at that time.

**Comment by antoninbas** [comment]
I got my answer: https://github.com/benmoss/go-powershell/pull/1#issuecomment-774105035. He recommends switching to a different fork.

**Comment by antoninbas** [comment]
@rakelkar I rebased the PR and fix the test failures.

By the way, do you have any insight about the difference between this package and the upstream K8s one: https://github.com/kubernetes/kubernetes/tree/master/pkg/util/netsh?

**Comment by antoninbas** [comment]
> @rakelkar I rebased the PR and fix the test failures.
> 
> By the way, do you have any insight about the difference between this package and the upstream K8s one: https://github.com/kubernetes/kubernetes/tree/master/pkg/util/netsh?

Actually there is no equivalent to https://github.com/rakelkar/gonetsh/tree/master/netroute in upstream K8s

**Comment by antoninbas** [comment]
@rakelkar friendly ping for this

**Review by rakelkar — APPROVED** [review]

**Pull request merged**
